releasetools: support prebuilt odm.img
Signing builds with prebuilt odm.img causes the following error:

Traceback (most recent call last):
  File "./build/make/tools/releasetools/sign_target_files_apks", line 1230, in <module>
    main(sys.argv[1:])
  File "./build/make/tools/releasetools/sign_target_files_apks", line 1223, in main
    add_img_to_target_files.main(new_args)
  File ".../build/make/tools/releasetools/add_img_to_target_files.py", line 942, in main
    AddImagesToTargetFiles(args[0])
  File ".../build/make/tools/releasetools/add_img_to_target_files.py", line 892, in AddImagesToTargetFiles
    CheckAbOtaImages(output_zip, ab_partitions)
  File ".../build/make/tools/releasetools/add_img_to_target_files.py", line 562, in CheckAbOtaImages
    assert available, "Failed to find " + img_name
AssertionError: Failed to find odm.img

This patch addresses this error by copying IMAGES/odm.img if it exists in the input zip

Test: Follow https://source.android.com/devices/tech/ota/sign_builds#release-keys and then
https: //source.android.com/devices/tech/ota/sign_builds#creating-image-files
Change-Id: I4908a2c36399425665ba34802b4186db97e58045
(cherry picked from commit 802c4ad5383563872612380308f1408ce19e34fa)